PROMPT Seeding demo schema and test data for the llmchat Oracle learning project.
PROMPT Apply with:
PROMPT   sqlplus appuser/AppUserPass123!@//127.0.0.1:1521/XEPDB1 @sql/oracle/seed_demo_data.sql
PROMPT This script creates four allowed tables: customers, products, orders, faq.

WHENEVER SQLERROR EXIT SQL.SQLCODE

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE faq CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE customers (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR2(100) NOT NULL,
  email_address VARCHAR2(150) NOT NULL UNIQUE,
  city VARCHAR2(80) NOT NULL,
  loyalty_tier VARCHAR2(20) NOT NULL
);

CREATE TABLE products (
  product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name VARCHAR2(120) NOT NULL,
  category_name VARCHAR2(60) NOT NULL,
  unit_price NUMBER(10,2) NOT NULL,
  active_flag CHAR(1) DEFAULT 'Y' NOT NULL,
  CONSTRAINT products_active_flag_chk CHECK (active_flag IN ('Y', 'N'))
);

CREATE TABLE orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  product_id NUMBER NOT NULL,
  order_date DATE NOT NULL,
  quantity NUMBER(4) NOT NULL,
  order_status VARCHAR2(20) NOT NULL,
  CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT orders_product_fk FOREIGN KEY (product_id) REFERENCES products(product_id),
  CONSTRAINT orders_quantity_chk CHECK (quantity > 0)
);

CREATE TABLE faq (
  faq_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_text VARCHAR2(300) NOT NULL,
  answer_text VARCHAR2(1000) NOT NULL,
  topic_name VARCHAR2(60) NOT NULL
);

INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Ada Lovelace', 'ada@example.com', 'London', 'gold');
INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Grace Hopper', 'grace@example.com', 'New York', 'gold');
INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Alan Turing', 'alan@example.com', 'Manchester', 'silver');
INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Katherine Johnson', 'katherine@example.com', 'White Sulphur Springs', 'platinum');
INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Donald Knuth', 'donald@example.com', 'Milwaukee', 'silver');
INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Margaret Hamilton', 'margaret@example.com', 'Paoli', 'gold');
INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Barbara Liskov', 'barbara@example.com', 'Los Angeles', 'bronze');
INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Linus Torvalds', 'linus@example.com', 'Helsinki', 'bronze');
INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Tim Berners-Lee', 'tim@example.com', 'London', 'silver');
INSERT INTO customers (customer_name, email_address, city, loyalty_tier) VALUES ('Radia Perlman', 'radia@example.com', 'Portsmouth', 'gold');

INSERT INTO products (product_name, category_name, unit_price, active_flag) VALUES ('Starter Laptop', 'hardware', 899.00, 'Y');
INSERT INTO products (product_name, category_name, unit_price, active_flag) VALUES ('Mechanical Keyboard', 'hardware', 129.00, 'Y');
INSERT INTO products (product_name, category_name, unit_price, active_flag) VALUES ('Noise Cancelling Headset', 'hardware', 219.00, 'Y');
INSERT INTO products (product_name, category_name, unit_price, active_flag) VALUES ('Cloud Backup Plan', 'subscription', 19.00, 'Y');
INSERT INTO products (product_name, category_name, unit_price, active_flag) VALUES ('Analytics Add-on', 'software', 49.00, 'Y');
INSERT INTO products (product_name, category_name, unit_price, active_flag) VALUES ('USB-C Dock', 'hardware', 159.00, 'Y');
INSERT INTO products (product_name, category_name, unit_price, active_flag) VALUES ('Legacy Support Pack', 'service', 299.00, 'N');
INSERT INTO products (product_name, category_name, unit_price, active_flag) VALUES ('Training Session', 'service', 399.00, 'Y');

INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (1, 2, DATE '2026-04-01', 1, 'shipped');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (1, 4, DATE '2026-04-02', 2, 'active');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (2, 1, DATE '2026-04-03', 1, 'processing');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (2, 5, DATE '2026-04-03', 1, 'active');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (3, 3, DATE '2026-04-04', 1, 'shipped');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (3, 6, DATE '2026-04-05', 1, 'processing');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (4, 1, DATE '2026-04-05', 3, 'shipped');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (4, 8, DATE '2026-04-06', 1, 'scheduled');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (5, 2, DATE '2026-04-06', 2, 'shipped');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (5, 4, DATE '2026-04-07', 1, 'active');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (6, 5, DATE '2026-04-07', 1, 'processing');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (6, 8, DATE '2026-04-08', 1, 'scheduled');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (7, 6, DATE '2026-04-08', 1, 'shipped');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (7, 4, DATE '2026-04-09', 1, 'cancelled');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (8, 1, DATE '2026-04-10', 1, 'processing');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (8, 2, DATE '2026-04-10', 1, 'processing');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (9, 3, DATE '2026-04-11', 2, 'shipped');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (9, 5, DATE '2026-04-12', 1, 'active');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (10, 8, DATE '2026-04-12', 1, 'scheduled');
INSERT INTO orders (customer_id, product_id, order_date, quantity, order_status) VALUES (10, 4, DATE '2026-04-13', 1, 'active');

INSERT INTO faq (question_text, answer_text, topic_name) VALUES ('How do I reset my password?', 'Use the account settings page and choose Reset Password. A reset link is emailed to you.', 'accounts');
INSERT INTO faq (question_text, answer_text, topic_name) VALUES ('How long does shipping take?', 'Hardware orders usually ship within two business days. Delivery depends on destination.', 'orders');
INSERT INTO faq (question_text, answer_text, topic_name) VALUES ('Can I cancel a subscription?', 'Yes. Subscription products can be cancelled from the billing page before the next renewal.', 'billing');
INSERT INTO faq (question_text, answer_text, topic_name) VALUES ('Which products are inactive?', 'Inactive products remain in the catalog for reporting but cannot be newly purchased.', 'products');
INSERT INTO faq (question_text, answer_text, topic_name) VALUES ('Do you offer onboarding help?', 'Yes. Training Session is a scheduled service product for onboarding or team enablement.', 'services');
INSERT INTO faq (question_text, answer_text, topic_name) VALUES ('How do loyalty tiers work?', 'Customers are assigned bronze, silver, gold, or platinum tiers based on account history.', 'customers');
INSERT INTO faq (question_text, answer_text, topic_name) VALUES ('Can I order multiple quantities?', 'Yes. The quantity field on an order records how many units were purchased.', 'orders');
INSERT INTO faq (question_text, answer_text, topic_name) VALUES ('Where can I find analytics features?', 'Analytics Add-on is listed in the software category and can be purchased separately.', 'products');

COMMIT;

PROMPT Seed complete.
PROMPT Row counts:
SELECT 'CUSTOMERS=' || COUNT(*) AS row_count FROM customers;
SELECT 'PRODUCTS=' || COUNT(*) AS row_count FROM products;
SELECT 'ORDERS=' || COUNT(*) AS row_count FROM orders;
SELECT 'FAQ=' || COUNT(*) AS row_count FROM faq;
