apiVersion: v1
kind: Service
metadata:
  name: oracle-host
  namespace: vault-demo
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - name: oracle
      port: 1521
      protocol: TCP
